### ISSUE TITLE
Add Daily Production Value (kWh) entity

### ISSUE THREAD

**Issue by sfrrcr** [edge-mining/addon-edge-mining#7]
Currently, the integration that reads data from the inverter in Home Assistant does not provide an entity for the actual daily energy production (in kWh). This data is crucial for monitoring and analyzing the performance of the photovoltaic system and comparing it with the theoretical production calculated by forecast.solar or any other add-on.

## Expected Behavior  
A new entity should be created to expose the actual daily energy production of the solar inverter in kWh.  

## Proposed Solution  
- Retrieve the daily energy production value from the inverter.  
- Create a new entity in Home Assistant to store and display this value.  
- Ensure the entity updates correctly and aligns with the inverter's reporting interval.  

## Additional Context  
This feature will allow users to track daily energy generation directly in Home Assistant, improving energy monitoring and enabling automation based on production levels.

**Comment by markoceri** [comment]
This result can be achived by creating two custom sensors, one that makes the integral of the power sensor and one that tracks the daily consumption.

### Step 1
Create a cumulative energy sensor starting from the inverter solar panel power sensor and make an integral sensor using the integration. Here is the reference guide [Guide](https://www.home-assistant.io/integrations/integration/)

```
# Sensore di integrazione potenza
#-----------------------------------
sensor:
  - platform: integration
    unique_id: voltronic_axpert_max_ii_pv1_charging_energy_total
    name: Totale energia prodotta da Voltronic Stringa 1
    source: sensor.voltronic_axpert_max_ii_pv1_charging_power
    unit_prefix: k
    round: 3
#-----------------------------------
````

### Step 2
Create an utility meter sensor with daily reset (or weekly, montly). Here is the reference guide [Guide](https://www.home-assistant.io/integrations/utility_meter/)

```
# Stringa 1 tramite integrazione HA
#-----------------------------------
utility_meter:
  voltronic_axpert_max_ii_pv1_charging_energy_daily:
    unique_id: voltronic_axpert_max_ii_pv1_charging_energy_daily
    name: Energia prodotta Oggi da Voltronic Stringa 1
    source: sensor.voltronic_axpert_max_ii_pv1_charging_energy_total
    cycle: daily
#-----------------------------------
```
